builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  main: ./cmd/hello/main.go
  binary: hello
  id: 'build-hello'
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  main: ./cmd/goodbye/main.go
  binary: goodbye
  id: 'build-goodbye'
