name: CI
on: push

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
  goreleaser:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Get Latest Release
      uses: abatilo/release-info-action@v1.0.0
      id: release-info
      with:
        owner: abatilo
        repo: go-releaser-testing
    - uses: actions/checkout@master
      with:
        ref: ${{ steps.release-info.outputs.latest_tag }}
    - env:
        TAG_REF: refs/tags/${{ steps.release-info.outputs.latest_tag }}
      run: |
        echo "::set-env name=GITHUB_REF::${TAG_REF}"
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
