name: CI
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/abatilo
      GOFLAGS: -mod=vendor
    strategy:
      matrix:
        include:
          - foo: bar
            bing: baz
          - foo: boop
            bing: beep
    steps:
      - run: |
          echo ${{ matrix.foo }}
          echo ${{ matrix.bing }}
