name: CI
on:
  push:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/abatilo
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Granting private modules access
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config --global url."https://x-access-token:${TOKEN}@github.com/abatilo".insteadOf "https://github.com/abatilo"

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.0"

      - uses: actions/checkout@v2
      - run: |
          go run main.go

      - env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          docker build --build-arg TOKEN=${TOKEN} -t private .
