name: CI
on:
  push:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_RUN_ID
  two:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_RUN_ID
