name: CI
on:
  push:
  workflow_dispatch:
  

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
        
        
    - name: Generate pre-release
      if: github.event_name == "push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
    - name: Generate release
      if: github.event_name == "workflow_dispatch"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release --branches "main"
